---
pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#changes-requested-reviews-by=0"
      - label!=do-not-merge
      - check-success=Validate Primer
    actions:
      merge:
        method: merge
        strict: true
