apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: primer
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/octo-emerging/gitops-primer:latest
        name: primer
        command: ["sleep", "3h"]
        env:
          - name: REPO
            value: git@github.com:cooktheryan/primer-poc.git
          - name: BRANCH
            value: stage
          - name: ACTION
            value: "alert"
          - name: IGNORE_OBJECT
            value: "secrets/secret-key"
        volumeMounts:
          - mountPath: /keys
            name: sshkey
          - name: repo
            mountPath: /repo
      securityContext:
       runAsUser: 0
      volumes:
      - name: sshkey
        secret:
          secretName: secret-key
          defaultMode: 0600
      - name: repo
        emptyDir: {}
      restartPolicy: Never
      serviceAccount: gitops-primer
