apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "primer.gitops.io/v1alpha1",
          "kind": "Export",
          "metadata": {
            "name": "export-sample"
          },
          "spec": {
            "foo": "bar"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.10.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: gitops-primer.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Export is the Schema for the exports API
      displayName: Export
      kind: Export
      name: exports.primer.gitops.io
      version: v1alpha1
  description: export and normalize kubernetes based yaml's for GitOps
  displayName: gitops-primer
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - users
          verbs:
          - impersonate
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - get
          - list
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - networking.k8s.io
          resources:
          - networkpolicies
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - primer.gitops.io
          resources:
          - exports
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - primer.gitops.io
          resources:
          - exports/finalizers
          verbs:
          - update
        - apiGroups:
          - primer.gitops.io
          resources:
          - exports/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: gitops-primer-controller-manager
      deployments:
      - name: gitops-primer-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:6d57bfd91fac9b68eb72d27226bc297472ceb136c996628b845ecc54a48b31cb
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                env:
                - name: DownloaderImageName
                  value: quay.io/konveyor/gitops-primer:v0.0.1
                - name: ExportImageName
                  value: quay.io/konveyor/gitops-primer-export:v0.0.1
                - name: OauthImageName
                  value: quay.io/openshift/origin-oauth-proxy:4.7
                image: quay.io/octo-emerging/gitops-primer:latest
                imagePullPolicy: IfNotPresent
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 100m
                    memory: 300Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: gitops-primer-controller-manager
              terminationGracePeriodSeconds: 10
      - name: gitops-primer-mutating-webhook-deployment
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: export-webhook
          strategy: {}
          template:
            metadata:
              labels:
                app: export-webhook
            spec:
              containers:
              - image: quay.io/octo-emerging/gitops-primer-webhook:latest
                imagePullPolicy: IfNotPresent
                name: export-webhook
                ports:
                - containerPort: 8000
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                volumeMounts:
                - mountPath: /tls
                  name: export-tls-secret
                  readOnly: true
              volumes:
              - name: export-tls-secret
                secret:
                  secretName: gitops-primer-mutating-webhook-deployment-service-cert
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: gitops-primer-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - gitops
  - operator
  links:
  - name: Gitops Primer
    url: https://gitops-primer.domain
  maturity: alpha
  provider:
    name: OCTO-ET
  version: 0.0.1
  webhookdefinitions:
  - admissionReviewVersions:
    - v1
    - v1beta1
    containerPort: 443
    deploymentName: gitops-primer-mutating-webhook-deployment
    failurePolicy: Fail
    generateName: mexport.kb.io
    rules:
    - apiGroups:
      - primer.gitops.io
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - exports
    sideEffects: None
    targetPort: 8000
    type: MutatingAdmissionWebhook
    webhookPath: /mutate
