apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: gitops-primer-webhook-service
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: controller-manager
status:
  loadBalancer: {}
