# permissions for end users to view extracts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extract-viewer-role
rules:
- apiGroups:
  - primer.gitops.io
  resources:
  - extracts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - primer.gitops.io
  resources:
  - extracts/status
  verbs:
  - get
