# permissions for end users to edit extracts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extract-editor-role
rules:
- apiGroups:
  - primer.gitops.io
  resources:
  - extracts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primer.gitops.io
  resources:
  - extracts/status
  verbs:
  - get
