
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cache.primer.gitops
  resources:
  - primers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.primer.gitops
  resources:
  - primers/finalizers
  verbs:
  - update
- apiGroups:
  - cache.primer.gitops
  resources:
  - primers/status
  verbs:
  - get
  - patch
  - update
