---
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 300
ignoreFailure: true
---
apiVersion: primer.gitops.io/v1alpha1
kind: Extract
metadata:
  name: ci
  namespace: test
status:
  completed: true
