---
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 100
collectors:
  - selector: job-name=primer-export-ci
---
apiVersion: primer.gitops.io/v1alpha1
kind: Export
metadata:
  name: ci
  namespace: test
