---
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 500
collectors:
  - selector: job-name=primer-export-ci
---
apiVersion: batch/v1
kind: Job 
metadata:
  name: primer-export-ci
  namespace: test
status:
  active: 1
